stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository
    - target/

before_script:
  - chmod +x mvnw

include:
  - local: spring-petclinic-admin-server/.gitlab-ci.yml
  - local: spring-petclinic-visits-service/.gitlab-ci.yml
  - local: spring-petclinic-vets-service/.gitlab-ci.yml
  - local: spring-petclinic-discovery-server/.gitlab-ci.yml
  - local: spring-petclinic-customers-service/.gitlab-ci.yml
  - local: spring-petclinic-config-server/.gitlab-ci.yml
  - local: spring-petclinic-api-gateway/.gitlab-ci.yml


.sast:
  stage: sast
  script:
    - spotbugs -effort:max -xml:withMessages -output spotbugs-report.xml

.dast:
  stage: dast
  script:
    - zap-cli -p 8080 -t http://your-app-url

.deploy:
  stage: deploy
  script:
    - scp target/your-app.jar user@your-server:/path/to/deployment
