build:
  script:
    - ./mvnw $MAVEN_CLI_OPTS clean install -PbuildDocker
  only:
    changes:
      - "spring-petclinic-spring-petclinic-api-gateway/**/*"

test:
  script:
    - ./mvnw $MAVEN_CLI_OPTS test
  only:
    changes:
      - "spring-petclinic-spring-petclinic-api-gateway/**/*"
